# Generated by Django 3.0.8 on 2020-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=12)),
                ('status', models.IntegerField(choices=[(1, 'Acquired'), (0, 'Available')], default=0)),
            ],
        ),
    ]
